CFLAGS = -Wall -g
all: ex11 ex12 ex13 ex14 ex15 ex16 ex17 ex18
ex11: ex11.c
	gcc $(CFLAGS) ex11.c -o ex11
ex12: ex12.c
	gcc $(CFLAGS) ex12.c -o ex12
ex13: ex13.c
	gcc $(CFLAGS) ex13.c -o ex13
ex14: ex14.c
	gcc $(CFLAGS) ex14.c -o ex14
ex15: ex15.c
	gcc $(CFLAGS) ex15.c -o ex15
ex16: ex16.c
	gcc $(CFLAGS) ex16.c -o ex16
ex17: ex17.c
	gcc $(CFLAGS) ex17.c -o ex17
ex18: ex18.c
	gcc $(CFLAGS) ex18.c -o ex18
clean:
	rm -f ex11 ex12 ex13 ex14 ex15 ex16 ex17 ex18
